"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Shield = exports.Seal = exports.Oil = exports.Oasis = exports.Horse = exports.Gold = exports.Gems = exports.Game = exports.Fish = exports.Coal = void 0;
var Coal_1 = require("@civ-clone/base-terrain-feature-coal/Coal");
Object.defineProperty(exports, "Coal", { enumerable: true, get: function () { return Coal_1.Coal; } });
var Fish_1 = require("@civ-clone/base-terrain-feature-fish/Fish");
Object.defineProperty(exports, "Fish", { enumerable: true, get: function () { return Fish_1.Fish; } });
var Game_1 = require("@civ-clone/base-terrain-feature-game/Game");
Object.defineProperty(exports, "Game", { enumerable: true, get: function () { return Game_1.Game; } });
var Gems_1 = require("@civ-clone/base-terrain-feature-gems/Gems");
Object.defineProperty(exports, "Gems", { enumerable: true, get: function () { return Gems_1.Gems; } });
var Gold_1 = require("@civ-clone/base-terrain-feature-gold/Gold");
Object.defineProperty(exports, "Gold", { enumerable: true, get: function () { return Gold_1.Gold; } });
var Horse_1 = require("@civ-clone/base-terrain-feature-horse/Horse");
Object.defineProperty(exports, "Horse", { enumerable: true, get: function () { return Horse_1.Horse; } });
var Oasis_1 = require("@civ-clone/base-terrain-feature-oasis/Oasis");
Object.defineProperty(exports, "Oasis", { enumerable: true, get: function () { return Oasis_1.Oasis; } });
var Oil_1 = require("@civ-clone/base-terrain-feature-oil/Oil");
Object.defineProperty(exports, "Oil", { enumerable: true, get: function () { return Oil_1.Oil; } });
var Seal_1 = require("@civ-clone/base-terrain-feature-seal/Seal");
Object.defineProperty(exports, "Seal", { enumerable: true, get: function () { return Seal_1.Seal; } });
var Shield_1 = require("@civ-clone/base-terrain-feature-shield/Shield");
Object.defineProperty(exports, "Shield", { enumerable: true, get: function () { return Shield_1.Shield; } });
//# sourceMappingURL=TerrainFeatures.js.map